In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [6]:
df = pd.read_csv('C:/Users/Payal Arora/Downloads/5-Days-Live-EDA-and-Feature-Engineering-main/5-Days-Live-EDA-and-Feature-Engineering-main/spam.csv')

In [7]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [9]:
df.columns

Index(['Category', 'Message'], dtype='object')

In [10]:
df.shape

(5572, 2)

In [11]:
df.isna().sum()

Category    0
Message     0
dtype: int64

In [12]:
df['Spam'] = df['Category'].apply(lambda x:1 if x=='spam' else 0)
df.head()

Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.Spam,test_size=0.20)

In [17]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [23]:
pipe=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())])

In [24]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [25]:
y_pred = pipe.predict(X_test)

In [26]:
from sklearn.metrics import accuracy_score, classification_report

In [27]:
score = accuracy_score(y_pred,y_test)
score

0.9874439461883409

In [28]:
report = classification_report(y_pred,y_test)

In [29]:
print(report)

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       975
           1       0.94      0.96      0.95       140

    accuracy                           0.99      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [30]:
emails=[
    'Sounds great! Are you home now?',
    'Will u meet ur dream partner soon? Is ur career off 2 a flyng start? 2 find out free, txt HORO followed by ur star sign, e. g. HORO ARIES'
]

In [31]:
pipe.predict(emails)

array([0, 1], dtype=int64)

In [32]:
random_rows = df.sample(n=2)

In [35]:
print(random_rows)

     Category                                            Message  Spam
4258     spam  important information 4 orange user . today is...     1
5327      ham                      Wishing you a wonderful week.     0


In [37]:
random_rows = random_rows['Message'].to_list()

In [38]:
print(random_rows)

["important information 4 orange user . today is your lucky day!2find out why log onto http://www.urawinner.com THERE'S A FANTASTIC SURPRISE AWAITING YOU!", 'Wishing you a wonderful week.']


In [39]:
pipe.predict(random_rows)

array([1, 0], dtype=int64)

In [40]:
random_rows = df.sample(n=2)

In [41]:
pipe.predict(random_rows)

array([0, 0, 0], dtype=int64)

In [43]:
print(random_rows)

     Category                                            Message  Spam
1446      ham                        I am in a marriage function     0
1679      ham  So many people seems to be special at first si...     0
